# Generated by Django 3.0.4 on 2020-05-02 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200402_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
