# Generated by Django 3.0.4 on 2020-05-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_product_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=0, max_length=13, unique=False),
            preserve_default=False,
        ),
    ]
